output_dir: ~/scratch/anna19/protein_confidence_output

dataset:
  class: EC
  path: {{ datadir }}
  percent: 95
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue
      - class: TruncateProtein
        max_length: 550

task:
  class: EarlyExitClassification_walltime_ProtBert
  model:
    class: CustomProtBert
    # path: {{ modeldir }}
    model: "CustomProtBert"
    dropout: 0.2
    batch_norm: True
  metric: 'f1_max'
  verbose: 1

optimizer:
  class: Adam
  lr: 1.0e-4

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

engine:
  gpus: [0]
  batch_size: 8
  log_interval: 1000

eval_metric: "f1_max"
freeze_model: True

# Load the model with all layers trained MLPs
load_weights_only: True
pretrained_mlp_load_bert: True
exit: True
num_layers: 30

###Model 01####
model_checkpoint: /shared/nas2/anna19/protein/early_exit/results/model_checkpoints/bert_ec/model_epoch49.pth
result_file: /shared/nas2/anna19/protein/early_exit/results/metrics/bert_ec_exit.csv