output_dir: ~/scratch/anna19/protein_confidence_output

dataset:
  class: SubcellularLocalization
  path: ~/scratch/anna19/subcell_localization/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 550
        random: True
      - class: ProteinView
        view: "residue"

task:
  class: EarlyExitProperty_continuous_protalbert
  model:
    class: CustomProtAlbert
    # path: {{ modeldir }}
    model: "CustomProtAlbert"
  metric: 'acc'
  verbose: 1
  num_mlp_layer: 2
  num_class: 10

optimizer:
  class: Adam
  lr: 1.0e-4

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

engine:
  gpus: [0]
  batch_size: 8
  log_interval: 1000

eval_metric: 'accuracy'
freeze_model: True
# Load the model with all layers trained MLPs
load_weights_only: True
pretrained_mlp_load_albert_property: True
exit_cl: True
num_layers: 12

###Model 01####
model_checkpoint:  /shared/nas2/anna19/protein/early_exit/results/model_checkpoints/albert_cl/model_epoch85.pth
result_file: /shared/nas2/anna19/protein/early_exit/results/metrics/albert_cl_exit.csv
