output_dir: ~/scratch/protein_output

dataset:
  class: SubcellularLocalization
  path: ~/scratch/anna19/cl/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue

task:
  class: PropertyPredictionAllLayers
  model:
    class: CustomESM2
    #path: {{ modeldir }}
    model: "CustomESM2"
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 10

optimizer:
  class: Adam
  lr: 5.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 4
  gradient_interval: 4

eval_metric: accuracy
lr_ratio: 0

model_checkpoint: {{ ckpt }}

train:
  num_epoch: 100

train_all_layers: True
checkpoint_path: '/shared/nas2/anna19/protein/early_exit/results/model_checkpoints/esm_cl'
evaluation_path_test: '/shared/nas2/anna19/protein/early_exit/results/metrics/esm_cl_evaluation_test'
evaluation_path_valid: '/shared/nas2/anna19/protein/early_exit/results/metrics/esm_cl_evaluation_valid'